version: '3.1'

services:
  enrollment_db:
    image: postgres
    restart: always
    container_name: enrollment_db
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: enrollment
      POSTGRES_PASSWORD: enroll_pass
      POSTGRES_INITDB_ARGS: "-A md5"
  app:
    build: .
    container_name: enrollment_app
    environment:
      - DATABASE_URL=postgresql://enrollment:enroll_pass@enrollment_db:5432/enrollment_db
    ports:
      - "80:80"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload "
    env_file:
      - .env
    depends_on:
      - enrollment_db
